apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
spec:
  type: {{ .Values.service.type }}
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
